"""attconf

Revision ID: eaffcfb8fa14
Revises: 32317f92ec90
Create Date: 2023-12-18 01:36:31.894378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaffcfb8fa14'
down_revision = '32317f92ec90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_attended', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registration', schema=None) as batch_op:
        batch_op.drop_column('is_attended')

    # ### end Alembic commands ###
